services:
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      JWT_SECRET: ${JWT_SECRET}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      NOMIC_API_KEY: ${NOMIC_API_KEY} 
      PYTHONUNBUFFERED: 1
      PORT: ${PORT}
      MAX_PDF_PAGES: ${MAX_PDF_PAGES:-1100}
      MAX_DOCUMENT_TOKENS: ${MAX_DOCUMENT_TOKENS:-1000000}
      APP_ENV: ${APP_ENV}



  #frontend:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
       # Vite requires these vars at BUILD time, not run time
  #      args:
  #        VITE_SUPABASE_URL: ${SUPABASE_URL}
  #        VITE_SUPABASE_KEY: ${SUPABASE_PUBLISHABLE_KEY}
  #        VITE_API_URL: http://localhost:8000
  #    ports:
  #      - "3000:80" # Access frontend at localhost:3000
  #    depends_on:
  #      - backend